name: Build Container for react app and push to live 
on:
  workflow_dispatch:
  push: 

jobs: 
  build-and-deploy-front:
    name: Build and Deploy Front-end
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kvnkrruk/ha_automationhelper_fe
        dockerfile: ha_automationhelper_fe/Dockerfile

    container_armsixtyfour_architecture_app_to_registry:
    name: Build and Deploy Docker image 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag kvnkrruk/ha_automationhelper_bf:latest \
            --platform linux/amd64,linux/arm64 .