name: Build Container for react app and push to live 
on:
  workflow_dispatch:
  push: 

jobs: 
  container_armsixtyfour_architecture_app_to_registry:
    name: Build and Deploy Docker image 
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag kvnkrruk/ha_automationhelper_fe:latest \
            --platform linux/amd64,linux/arm64 .
  ssh_container_to_rpfour:
    name: update server
    needs: "container_armsixtyfour_architecture_app_to_registry"
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 200m
        script: 
          echo "${{ secrets.PASSWORD }}" | sudo -S ./UpdateFE.sh
          #echo ${{ secrets.PASSWORD }} | sudo -S docker stop my-fe-helper-app
          #echo ${{ secrets.PASSWORD }} | sudo -S docker rm   my-fe-helper-app
          #echo ${{ secrets.PASSWORD }} | sudo -S docker rmi  kvnkrruk/ha_automationhelper_fe
          #echo ${{ secrets.PASSWORD }} | sudo -S docker network create my_helpernetwork
          #echo ${{ secrets.PASSWORD }} | sudo -S docker run -t -d -p 3000:3000 --name my-fe-helper-app --network my_helpernetwork kvnkrruk/ha_automationhelper_fe
          #echo ${{ secrets.PASSWORD }} | sudo -S docker run -t -d -p 3000:3000 --name my-fe-helper-app --network my_helper_network kvnkrruk/ha_automationhelper_fe
            